const shopData = [
    {
      id: 1,
      company: "levis",
      image: "/assets/products/f1.jpg",
      price: "49.9",
      Heading: "Men's Dri-FIT T-Shirt",
      rating:3.5,
      stock:69,
    },
    {
      id: 2,
      company: "nike",
      image: "/assets/products/f2.jpg",
      price: "42.9",
      Heading: "Slim Fit Dress Shirt",
      rating:3.5,
      stock:45,
    },
    {
      id: 3,
      company: "addidas",
      image: "/assets/products/f3.jpg",
      price: "44.9",
      Heading: "Men's Dri-FIT T-Shirt",
      rating:3.5,
      stock:79,
    },
    {
      id: 4,
      company: "nike",
      image: "/assets/products/f4.jpg",
      price: "49.9",
      Heading: "Men's 1950s Sportswear",
      rating:3.5,
      stock:95,
    },
    {
      id: 5,
      company: "addidas",
      image: "/assets/products/f5.jpg",
      price: "49.9",
      Heading: "Men's 1950s Sportswear",
      rating:3.5,
      stock:105,
    },
    {
      id: 6,
      company: "nike",
      image: "/assets/products/f6.jpg",
      price: "49.9",
      Heading: "Men's Dri-FIT T-Shirt",
      rating:3.5,
      stock:61,
    },
    {
      id: 7,
      company: "levis",
      image: "/assets/products/f7.jpg",
      price: "49.9",
      Heading: "Slim Fit Dress Shirt",
      rating:3.5,
      stock:75,
    },
    {
      id: 8,
      company: "nike",
      image: "/assets/products/f8.jpg",
      price: "49.9",
      Heading: "Slim Fit Dress Shirt",
      rating:3.5,
      stock:85,
    },
    {
      id: 9,
      company: "levis",
      image: "/assets/products/img-4.png",
      price: "49.9",
      Heading: "Men's Dri-FIT T-Shirt",
      rating:3.5,
      stock:55,
    },
    {
      id: 10,
      company: "addidas",
      image: "/assets/products/img1.png",
      price: "49.9",
      Heading: "Men's Dri-FIT T-Shirt",
      rating:3.5,
      stock:58,
    },
    {
      id: 11,
      company: "nike",
      image: "/assets/products/n6.jpg",
      price: "49.9",
      Heading: "Women's Basic Tee, Men's Rebel Bold Tee",
      rating:3.5,
      stock:75,
    },
    {
      id: 12,
      company: "levis",
      image: "/assets/products/img3.png",
      price: "49.9",
      Heading: "Women's Badge of Sport Tee",
      rating:3.5,
      stock:95,
    },
  
    {
      id: 13,
      company: "nike",
      image: "/assets/products/img4.png",
      price: "49.9",
      Heading: "Men's 1950s Sportswear",
      rating:4,
      stock:82,
    },
    {
      id: 14,
      company: "addidas",
      image: "/assets/products/img5.png",
      price: "49.9",
      Heading: "Men's Dri-FIT T-Shirt",
      rating:4,
      stock:95,
    },
    {
      id: 15,
      company: "nike",
      image: "/assets/products/img6.png",
      price: "49.9",
      Heading: "Women's Badge of Sport Tee",
      rating:3.5,
      stock:77,
    },
    {
      id: 17,
      company: "levis",
      image: "/assets/products/n7.jpg",
      price: "49.9",
      Heading: "Women's Badge of Sport Tee",
      rating:3.5,
      stock:90,
    },
    {
      id: 18,
      company: "addidas",
      image: "/assets/products/n8.jpg",
      price: "49.9",
      Heading: "Men's Cotton Classic Short Sleeve Crew Neck T-Shirt",
      rating:4.2,
      stock:80,
    },
    {
      id: 19,
      company: "levis",
      image: "/assets/products/n2.jpg",
      price: "49.9",
      Heading: "Women's Basic Tee, Men's Rebel Bold Tee",
      rating:4.5,
      stock:95,
    },
    {
      id: 20,
      company: "nike",
      image: "/assets/products/n1.jpg",
      price: "49.9",
      Heading: "Men's 1950s Sportswear",
      rating:3.5,
      stock:93,
    },
    {
      id: 21,
      company: "levis",
      image: "/assets/products/n2.jpg",
      price: "49.9",
      Heading: "Women's Badge of Sport Tee",
      rating:3.5,
      stock:67,
    },
    {
      id: 22,
      company: "levis",
      image: "/assets/products/n3.jpg",
      price: "49.9",
      Heading: "Slim Fit Dress Shirt",
      rating:3.5,
      stock:95,
    },
    {
      id: 23,
      company: "levis",
      image: "/assets/products/n4.jpg",
      price: "49.9",
      Heading: "Women's Basic Tee, Men's Rebel Bold Tee",
      rating:4.5,
      stock:29,
    },
    {
      id: 24,
      company: "nike",
      image: "/assets/products/n4.jpg",
      price: "49.9",
      Heading: "Slim Fit Dress Shirt",
      rating:3.5,
      stock:100,
    },
    {
      id: 25,
      company: "levis",
      image: "/assets/products/n5.jpg",
      price: "49.9",
      Heading: "Slim Fit Dress Shirt",
      rating:3.5,
      stock:97,
    },
    {
      id: 25,
      company: "addidas",
      image: "/assets/products/img5.png",
      price: "49.9",
      Heading: "Women's Basic Tee, Men's Rebel Bold Tee",
      rating:5,
      stock:57,
    },
    {
      id: 26,
      company: "levis",
      image: "/assets/products/img6.png",
      price: "49.9",
      Heading: "Slim Fit Dress Shirt",
      rating:3.5,
      stock:95,
    },
  ];
  export default shopData;