const shopData = [
  {
    id: 31,
    company: "levis",
    image: "../assets/products/f1.jpg",
    price: "49.9",
    Heading: "Men's Dri-FIT T-Shirt",
    rating:3.5,
    stock:95,
  },
  {
    id: 32,
    company: "nike",
    image: "../assets/products/f2.jpg",
    price: "42.9",
    Heading: "Slim Fit Dress Shirt",
    rating:3.5,
    stock:95,
  },
  {
    id: 33,
    company: "addidas",
    image: "../assets/products/f3.jpg",
    price: "44.9",
    Heading: "Men's Dri-FIT T-Shirt",
    rating:3.5,
    stock:95,
  },
  {
    id: 34,
    company: "nike",
    image: "../assets/products/f4.jpg",
    price: "49.9",
    Heading: "Men's 1950s Sportswear",
    rating:3.5,
    stock:95,
  },
  {
    id: 35,
    company: "addidas",
    image: "../assets/products/f5.jpg",
    price: "49.9",
    Heading: "Men's 1950s Sportswear",
    rating:3.5,
    stock:95,
  },
  {
    id: 36,
    company: "nike",
    image: "../assets/products/f6.jpg",
    price: "49.9",
    Heading: "Men's Dri-FIT T-Shirt",
    rating:3.5,
    stock:95,
  },
  {
    id: 37,
    company: "levis",
    image: "../assets/products/f7.jpg",
    price: "49.9",
    Heading: "Slim Fit Dress Shirt",
    rating:3.5,
    stock:95,
  },
  {
    id: 38,
    company: "nike",
    image: "../assets/products/f8.jpg",
    price: "49.9",
    Heading: "Slim Fit Dress Shirt",
    rating:3.5,
    stock:95,
  },
  {
    id: 39,
    company: "levis",
    image: "../assets/products/img-4.png",
    price: "49.9",
    Heading: "Men's Dri-FIT T-Shirt",
    rating:3.5,
    stock:95,
  },
  {
    id: 40,
    company: "addidas",
    image: "../assets/products/img1.png",
    price: "49.9",
    Heading: "Men's Dri-FIT T-Shirt",
    rating:3.5,
    stock:95,
  },
  {
    id: 41,
    company: "nike",
    image: "../assets/products/n6.jpg",
    price: "49.9",
    Heading: "Women's Basic Tee, Men's Rebel Bold Tee",
    rating:3.5,
    stock:95,
  },
  {
    id: 42,
    company: "levis",
    image: "../assets/products/img3.png",
    price: "49.9",
    Heading: "Women's Badge of Sport Tee",
    rating:3.5,
    stock:95,
  },

  {
    id: 43,
    company: "nike",
    image: "../assets/products/img4.png",
    price: "49.9",
    Heading: "Men's 1950s Sportswear",
    rating:4,
    stock:95,
  },
  {
    id: 44,
    company: "addidas",
    image: "../assets/products/img5.png",
    price: "49.9",
    Heading: "Men's Dri-FIT T-Shirt",
    rating:4,
    stock:95,
  },
  {
    id: 45,
    company: "nike",
    image: "../assets/products/img6.png",
    price: "49.9",
    Heading: "Women's Badge of Sport Tee",
    rating:3.5,
    stock:95,
  },
  {
    id: 47,
    company: "levis",
    image: "../assets/products/n7.jpg",
    price: "49.9",
    Heading: "Women's Badge of Sport Tee",
    rating:3.5,
    stock:95,
  },
  {
    id: 48,
    company: "addidas",
    image: "../assets/products/n8.jpg",
    price: "49.9",
    Heading: "Men's Cotton Classic Short Sleeve Crew Neck T-Shirt",
    rating:4.2,
    stock:95,
  },
  {
    id: 49,
    company: "levis",
    image: "../assets/products/n2.jpg",
    price: "49.9",
    Heading: "Women's Basic Tee, Men's Rebel Bold Tee",
    rating:3.5,
    stock:95,
  },
  {
    id: 50,
    company: "nike",
    image: "../assets/products/n1.jpg",
    price: "49.9",
    Heading: "Men's 1950s Sportswear",
    rating:3.5,
    stock:95,
  },
  {
    id: 51,
    company: "levis",
    image: "../assets/products/n2.jpg",
    price: "49.9",
    Heading: "Women's Badge of Sport Tee",
    rating:3.5,
    stock:95,
  },
  {
    id: 52,
    company: "levis",
    image: "../assets/products/n3.jpg",
    price: "49.9",
    Heading: "Slim Fit Dress Shirt",
    rating:3.5,
    stock:95,
  },
  {
    id: 53,
    company: "levis",
    image: "../assets/products/n4.jpg",
    price: "49.9",
    Heading: "Women's Basic Tee, Men's Rebel Bold Tee",
    rating:4.5,
    stock:95,
  },
  {
    id: 54,
    company: "nike",
    image: "../assets/products/n4.jpg",
    price: "49.9",
    Heading: "Slim Fit Dress Shirt",
    rating:3.5,
    stock:95,
  },
  {
    id: 55,
    company: "levis",
    image: "../assets/products/n5.jpg",
    price: "49.9",
    Heading: "Slim Fit Dress Shirt",
    rating:3.5,
    stock:95,
  },
  {
    id: 55,
    company: "addidas",
    image: "../assets/products/img5.png",
    price: "49.9",
    Heading: "Women's Basic Tee, Men's Rebel Bold Tee",
    rating:5,
    stock:95,
  },
  {
    id: 56,
    company: "levis",
    image: "../assets/products/img6.png",
    price: "49.9",
    Heading: "Slim Fit Dress Shirt",
    rating:3.5,
    stock:95,
  },
];
export default shopData;
